# Generated by Django 4.2 on 2023-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d'),
        ),
    ]
